### ISSUE TITLE
elasticsearch client/server version mismatch? 

### ISSUE THREAD

**Issue by loicjaouen** [loicjaouen/arches_issues#6]
at one point `docker compose up` shows this:
```
arches         |   File "/web_root/arches/arches/app/search/search_engine_factory.py", line 38, in create
arches         |     return getattr(_temp, classname)(hosts=hosts, prefix=prefix, **connection_options)
arches         |   File "/web_root/arches/arches/app/search/search.py", line 41, in __init__
arches         |     self.es = Elasticsearch(serializer=serializer, **kwargs)
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py", line 330, in __init__
arches         |     node_configs = client_node_configs(
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 105, in client_node_configs
arches         |     node_configs = hosts_to_node_configs(hosts)
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 154, in hosts_to_node_configs
arches         |     node_configs.append(host_mapping_to_node_config(host))
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 221, in host_mapping_to_node_config
arches         |     return NodeConfig(**options)  # type: ignore
arches         | TypeError: NodeConfig.__init__() missing 1 required positional argument: 'scheme'
```

it looks like a client/server version mismatch

**Comment by loicjaouen** [comment]
https://pypi.org/project/elasticsearch/ says:
> Language clients are forward compatible; meaning that clients support communicating with greater or equal minor versions of Elasticsearch. Elasticsearch language clients are only backwards compatible with default distributions and without guarantees made.
>
> If you have a need to have multiple versions installed at the same time older versions are also released as elasticsearch2 and elasticsearch5.

we seem to have client on (from `requirements.txt`):
> elasticsearch>=8.3.1,<9.0.0

and server on (from `docker-compose.yml`)
> elasticsearch:7.5.1

**Comment by loicjaouen** [comment]
arches v7.3 lists in it dependencies elasticsearch v8, updating `docker-compose.yml` then

**Comment by loicjaouen** [comment]
gives an error:
```
elasticsearch  | Exception in thread "main" org.elasticsearch.ElasticsearchParseException: null-valued setting found for key [discovery.seed_hosts] found at line number [1], column number [22]
elasticsearch  | 	at org.elasticsearch.common.settings.Settings.validateValue(Settings.java:804)
elasticsearch  | 	at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:779)
elasticsearch  | 	at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:723)
elasticsearch  | 	at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1226)
elasticsearch  | 	at org.elasticsearch.node.InternalSettingsPreparer.loadOverrides(InternalSettingsPreparer.java:143)
elasticsearch  | 	at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:53)
elasticsearch  | 	at org.elasticsearch.common.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:110)
elasticsearch  | 	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
elasticsearch  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
elasticsearch  | 	at org.elasticsearch.cli.Command.main(Command.java:50)
elasticsearch  | 	at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
elasticsearch exited with code 1
```

**Comment by loicjaouen** [comment]
I guess this is: https://github.com/archesproject/arches/blob/stable/7.3.0/docker-compose.yml#L84

**Comment by loicjaouen** [comment]
removing the line
```
        - discovery.seed_hosts=
```

this version of ES doesn't like it left empty, it default is :
```
["127.0.0.1", "[::1]"]
```

which is fine for a single ES node

**Comment by loicjaouen** [comment]
next:
```
Failed to bind service","error.stack_trace":"org.elasticsearch.ElasticsearchException: failed to bind service
    at org.elasticsearch.server@8.7.0/org.elasticsearch.node.Node.<init>(Node.java:1148)
    at org.elasticsearch.server@8.7.0/org.elasticsearch.node.Node.<init>(Node.java:324)
    at org.elasticsearch.server@8.7.0/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:216)
    at org.elasticsearch.server@8.7.0/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:216)
    at org.elasticsearch.server@8.7.0/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
Caused by: org.elasticsearch.gateway.CorruptStateException: Format version is not supported. Upgrading to [8.7.0] is only supported from version [7.17.0].
    at org.elasticsearch.server@8.7.0/org.elasticsearch.env.NodeEnvironment.checkForIndexCompatibility(NodeEnvironment.java:515)
    at org.elasticsearch.server@8.7.0/org.elasticsearch.env.NodeEnvironment.upgradeLegacyNodeFolders(NodeEnvironment.java:414)
    at org.elasticsearch.server@8.7.0/org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:307)
    at org.elasticsearch.server@8.7.0/org.elasticsearch.node.Node.<init>(Node.java:480)
    ... 4 more
```

**Comment by loicjaouen** [comment]
- we start from a fresh install there is nothing to port
- the docker-compose pass no config file
- the rest of the communication is supposed to be passed by python package that is compatible

What's wrong?

**Comment by loicjaouen** [comment]
where is the error: the above log is from `arches` but the exception is thrown at the server side (`org.elasticsearch.server@8.7.0`).

**Comment by loicjaouen** [comment]
removed `nginx`, `arches` and `db` and their volumes

restarted, we are back with the error:
```
missing 1 required positional argument: 'scheme'
```

**Comment by loicjaouen** [comment]
above commit : 
- adds the `scheme` to the ES client args
- amends the entrypoint script to use that `scheme`
- adapts the env var passed to the add the `scheme`
- force the parsing of port into an int

**Comment by loicjaouen** [comment]
now:
```
db             | 2023-04-12 16:29:49.812 UTC [178] postgres@arches ERROR:  column nodes.isrequired does not exist at character 215
db             | 2023-04-12 16:29:49.812 UTC [178] postgres@arches STATEMENT:  SELECT "nodes"."nodeid", "nodes"."name", "nodes"."description", "nodes"."istopnode", "nodes"."ontologyclass", "nodes"."datatype", "nodes"."nodegroupid", "nodes"."graphid", "nodes"."config", "nodes"."issearchable", "nodes"."isrequired", "nodes"."sortorder", "nodes"."fieldname", "nodes"."exportable", "nodes"."alias", "nodes"."hascustomalias" FROM "nodes" WHERE "nodes"."graphid" = 'ff623370-fa12-11e6-b98b-6c4008b05c4c'::uuid
arches         | [2023-04-12 16:29:49 +0000] [91] [ERROR] Exception in worker process
arches         | Traceback (most recent call last):
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
arches         |     return self.cursor.execute(sql, params)
arches         | psycopg2.errors.UndefinedColumn: column nodes.isrequired does not exist
arches         | LINE 1: ...aphid", "nodes"."config", "nodes"."issearchable", "nodes"."i...
```

**Comment by loicjaouen** [comment]
there is still an error:
```
arches         | deleting index : arches_terms
arches         | Traceback (most recent call last):
arches         |   File "/web_root/arches/manage.py", line 27, in <module>
arches         |     execute_from_command_line(sys.argv)
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
arches         |     utility.execute()
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
arches         |     self.fetch_command(subcommand).run_from_argv(self.argv)
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
arches         |     self.execute(*args, **cmd_options)
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
arches         |     output = self.handle(*args, **options)
arches         |   File "/web_root/arches/arches/management/commands/setup_db.py", line 52, in handle
arches         |     self.setup_db()
arches         |   File "/web_root/arches/arches/management/commands/setup_db.py", line 190, in setup_db
arches         |     management.call_command("es", operation="delete_indexes")
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/django/core/management/__init__.py", line 181, in call_command
arches         |     return command.execute(*args, **defaults)
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
arches         |     output = self.handle(*args, **options)
arches         |   File "/web_root/arches/arches/management/commands/es.py", line 158, in handle
arches         |     self.delete_indexes(name=options["name"])
arches         |   File "/web_root/arches/arches/management/commands/es.py", line 277, in delete_indexes
arches         |     delete_terms_index()
arches         |   File "/web_root/arches/arches/app/search/mappings.py", line 97, in delete_terms_index
arches         |     se.delete_index(index=TERMS_INDEX)
arches         |   File "/web_root/arches/arches/app/search/search.py", line 116, in delete_index
arches         |     return self.es.indices.delete(ignore=[400, 404], **kwargs)
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
arches         |     return api(*args, **kwargs)
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/elasticsearch/_sync/client/indices.py", line 690, in delete
arches         |     return self.perform_request(  # type: ignore[return-value]
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 389, in perform_request
arches         |     return self._client.perform_request(
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 285, in perform_request
arches         |     meta, resp_body = self.transport.perform_request(
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/elastic_transport/_transport.py", line 329, in perform_request
arches         |     meta, raw_data = node.perform_request(
arches         |   File "/web_root/ENV/lib/python3.10/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
arches         |     raise err from None
arches         | elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fe41c089a80>: Failed to establish a new connection: [Errno 111] Connection refused))
```

**Comment by loicjaouen** [comment]
the whole build take too long, restaging, change build name and version number (in commit above)

**Comment by loicjaouen** [comment]
we fail to access elasticsearch

have things changed since the previous ES docker stock image version?

starting the previously used version: 

```bash
docker run --name estest -p 9400:9200 -p 9500:9300 -e "discovery.type=single-node" elasticsearch:7.5.1
```

testing it on another terminal:

```bash
$ curl -v http://localhost:9400/_cluster/health?pretty
*   Trying 127.0.0.1:9400...
* Connected to localhost (127.0.0.1) port 9400 (#0)
> GET /_cluster/health?pretty HTTP/1.1
> Host: localhost:9400
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 467
< 
{
  "cluster_name" : "docker-cluster",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 0,
  "active_shards" : 0,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
* Connection #0 to host localhost left intact
```

testing the new version as started the same way (with more ram otherwise it crashes):

```bash
docker rm estest
docker run --name estest -m 4GB -p 9400:9200 -p 9500:9300 -e "discovery.type=single-node" elasticsearch:8.7.0
```

trying to access it:

```bash
$ curl -v http://localhost:9400/_cluster/health?pretty
*   Trying 127.0.0.1:9400...
* Connected to localhost (127.0.0.1) port 9400 (#0)
> GET /_cluster/health?pretty HTTP/1.1
> Host: localhost:9400
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

and ES log says:

```
received plaintext http traffic on an https channel, closing connection
```

trying on https, without check for cert:

```bash
curl -kv https://localhost:9400/_cluster/health?pretty
```

which complains about authentication, default user/password values fails.

Erasing default values...

**Comment by loicjaouen** [comment]
getting the ES default config above with:
```bash
docker cp elasticsearch:/usr/share/elasticsearch/config/elasticsearch.yml docker/elasticsearch.yml
```

**Comment by loicjaouen** [comment]
removed https and authentication in above commit
